### ISSUE TITLE
rebin issue

### ISSUE THREAD

**Issue by blehman** [jeffakolb/Gnip-Trend-Detection#4]
(py27) [tw-mbp-blehman Gnip-Trend-Detection]$ cat example/example.csv | ./trend_rebin.py -c example/config.cfg 
Traceback (most recent call last):
  File "./trend_rebin.py", line 14, in <module>
    from gnip_trend_detection.analysis import rebin
  File "/Users/blehman/workspace/github_repos/Gnip-Trend-Detection/gnip_trend_detection/analysis.py", line 9, in <module>
    import datetime_truncate 
ImportError: No module named datetime_truncate

**Comment by jeffakolb** [comment]
Added datetime_truncate to requirements.
